name: Build and Publish

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish Windows
        run: dotnet publish --configuration Release -r win-x64 --no-self-contained
      - name: Publish Linux
        run: dotnet publish --configuration Release -r linux-x64 --no-self-contained
      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: FileMover_win-x64
          path: /home/runner/work/FileMover/FileMover.Console/bin/Release/net6.0/win-x64/publish/
      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: FileMover_linux-x64
          path: /home/runner/work/FileMover/FileMover.Console/bin/Release/net6.0/linux-x64/publish/
